### ISSUE TITLE
Explicit which projection is used in documentation

### ISSUE THREAD

**Issue by davidAlgis** [MichaelTaylor3D/UnityGPSConverter#6]
Hi, 
Could you explicit which projection is being used between GPS to UCS ?

```
float m1 = 111132.92f;    // latitude calculation term 1
float m2 = -559.82f;        // latitude calculation term 2
float m3 = 1.175f;      // latitude calculation term 3
float m4 = -0.0023f;        // latitude calculation term 4
float p1 = 111412.84f;    // longitude calculation term 1
float p2 = -93.5f;      // longitude calculation term 2
float p3 = 0.118f;      // longitude calculation term 3
```
This way, we could understand where these constants comes from.

**Comment by MichaelTaylor3d** [comment]
Hi David,

I wrote this so long ago, I don't remember where the numbers came from.

Sorry About that,
Michael

**Comment by davidAlgis** [comment]
Ok thanks anyway and for the projection don't you remember ?
(I sent you an email too, don't take it into consideration ^^)

**Comment by davidAlgis** [comment]
Ok I find it : https://en.wikipedia.org/wiki/Geographic_coordinate_system#Length_of_a_degree
